### ISSUE TITLE
EncryptionGenerator.jar

### ISSUE THREAD

**Issue by conder** [inbloom/APP-dashboard#2]
I am trying to setup this application against my SLC sandbox dataset.  The alpha README indicates this jar file is included for encrypting the oauth client id/secret.  I build the project and do not see this EncryptionGenerator.jar anywhere.

**Comment by jasonhoekstra** [comment]
Hi @conder - the app should have still operated without this jar, but we just checked it into the head branch to ensure all files are there.  Please give this another shot and let us know if it works!

**Comment by conder** [comment]
Jason,

Thanks.  I see that you removed it again pending some technical issues.

Must I encrypt the credentials for the application to work?

Thanks,
Joseph Conder

On Oct 2, 2012, at 1:35 PM, Jason Hoekstra wrote:

Hi @conderhttps://github.com/conder - the app should have still operated without this jar, but we just checked it into the head branch to ensure all files are there. Please give this another shot and let us know if it works!
